name: Rotate Secret Value

on:
  workflow_dispatch: # Allows you to manually trigger it

jobs:
  rotate-secret:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - name: Generate new secret value
        id: generate
        run: |
          NEW_VALUE="rotated_value_$(date +%s)"
          echo "NEW_SECRET=$NEW_VALUE" >> $GITHUB_ENV

      - name: Fetch repository public key
        id: get-key
        run: |
          repo=$(echo "${{ github.repository }}" | sed 's/\//%2F/g')
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/secrets/public-key \
            > public_key.json
          echo "KEY_ID=$(jq -r .key_id public_key.json)" >> $GITHUB_ENV
          echo "PUBLIC_KEY=$(jq -r .key public_key.json)" >> $GITHUB_ENV

      - name: Encrypt the new secret value
        id: encrypt
        run: |
          echo "${{ env.NEW_SECRET }}" | \
            openssl rsautl -encrypt -pubin -inkey <(echo "${{ env.PUBLIC_KEY }}" | base64 --decode) | \
            base64 -w 0 > encrypted_secret.txt
          echo "ENCRYPTED_VALUE=$(cat encrypted_secret.txt)" >> $GITHUB_ENV

      - name: Update secret via GitHub API
        run: |
          SECRET_NAME="MY_SECRET_NAME" # <- change this to your secret name
          curl -X PUT \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/secrets/$SECRET_NAME \
            -d @- <<EOF
          {
            "encrypted_value": "${{ env.ENCRYPTED_VALUE }}",
            "key_id": "${{ env.KEY_ID }}"
          }
          EOF
